CREATE VIEW [dbo].[BlockView]
WITH SCHEMABINDING 
	AS Select [Id]
      ,[Hash]
      ,[Size]
      ,[Version]
      ,[PreviousBlockHash]
      ,[NextBlockHash]
      ,[Merkleroot]
      ,[Time]
      ,[Index]
      ,[Nonce]
      ,[NextConsensus]
      ,[TxCount]
      ,[Sys_Fee]
      ,[Net_Fee]
  FROM dbo.[Block]
